server:
  port: 10301

spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.115/wl_dev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=CTT
    username: vortex
    password: vortex2016
    initial-size: 10
    max-wait: 10000
    maximum-pool-size: 10
    max-active: 10
    max-idle: 2
    minIdle: 2
    test-on-borrow: false
    test-on-return: true
    test-while-idle: true
    validation-query: select 1


spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test




